const modal=document.querySelector('#modal');const content=document.querySelector('#modalContent');const toast=document.querySelector('#toast');let lastFocus=null;let db;
const DB_NAME='BotMedicRosasPata';const DB_VERSION=1;
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=e=>{const d=e.target.result;['profiles','interactions','reminders','feedback'].forEach(store=>{if(!d.objectStoreNames.contains(store))d.createObjectStore(store,{keyPath:'id',autoIncrement:true})})};req.onsuccess=()=>{db=req.result;resolve(db)};req.onerror=()=>reject(req.error)})}
async function addRecord(store,value){if(!db)await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');const req=tx.objectStore(store).add({...value,createdAt:new Date().toISOString()});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function getAll(store){if(!db)await openDB();return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function clearAll(){if(!db)await openDB();await Promise.all(['profiles','interactions','reminders','feedback'].map(store=>new Promise((resolve,reject)=>{const req=db.transaction(store,'readwrite').objectStore(store).clear();req.onsuccess=resolve;req.onerror=reject})))}
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
function showModal(html){lastFocus=document.activeElement;content.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>modal.querySelector('button,input,a')?.focus(),20)}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';lastFocus?.focus()}
document.addEventListener('click',e=>{const opener=e.target.closest('[data-open]');if(opener)openFeature(opener.dataset.open);if(e.target.closest('[data-close]'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});

const templates={
 emergency:()=>`<span class="kicker">AYUDA INMEDIATA</span><h2 id="modalTitle">Centro de emergencia</h2><p class="modal-lead">Si existe peligro inmediato, llama al servicio adecuado. Los números corresponden a servicios oficiales del Perú.</p><div class="alert-box">⚠️ Mantén la calma, indica tu ubicación y describe brevemente lo sucedido.</div><div class="emergency-list"><a class="call-card danger" href="tel:106"><div><strong>SAMU · Urgencia médica</strong><small>Número 106</small></div><span>Llamar ☎</span></a><a class="call-card" href="tel:116"><div><strong>Bomberos</strong><small>Número 116</small></div><span>Llamar ☎</span></a><a class="call-card" href="tel:105"><div><strong>Policía Nacional</strong><small>Número 105</small></div><span>Llamar ☎</span></a><a class="call-card" href="tel:113"><div><strong>Línea 113 Salud</strong><small>Orientación gratuita · Opción 5 salud mental</small></div><span>Llamar ☎</span></a></div><button class="secondary-btn" id="shareLocation">📍 Compartir mi ubicación</button>`,
 firstAid:()=>`<span class="kicker">GUÍAS EDUCATIVAS</span><h2 id="modalTitle">Primeros auxilios</h2><p class="modal-lead">Elige una situación. Si la persona no responde, no respira normalmente o está en peligro, solicita ayuda profesional de inmediato.</p><div class="aid-grid">${[['🩸','Sangrado','bleeding'],['🔥','Quemadura','burn'],['😵','Desmayo','faint'],['🤧','Atragantamiento','choke'],['🦶','Golpe o torcedura','sprain'],['🌡️','Fiebre o malestar','fever']].map(x=>`<button class="aid-card" data-aid="${x[2]}"><span>${x[0]}</span><strong>${x[1]}</strong></button>`).join('')}</div><div class="safe-box">🛡️ Estas guías son generales. No realices maniobras para las que no estés capacitado.</div>`,
 calm:()=>`<div class="breath-modal"><span class="kicker">PAUSA CON MEDIC</span><h2 id="modalTitle">Respira conmigo</h2><p class="modal-lead">Sigue el círculo: inhala suavemente, sostén y exhala despacio. Detente si te sientes incómodo.</p><div class="breath-circle" id="breathCircle">Inhala</div><div class="timer" id="calmTimer">01:00</div><button class="primary-btn" id="startCalm">Comenzar</button><div class="safe-box">Si te sientes en crisis, estás en peligro o piensas hacerte daño, busca a un adulto de confianza y llama al 113, opción 5.</div></div>`,
 profile:()=>`<span class="kicker">DATOS VOLUNTARIOS</span><h2 id="modalTitle">Mi ficha preventiva</h2><p class="modal-lead">Se guarda solamente en la base de datos de este navegador. No compartas información sensible en un equipo público.</p><form id="profileForm" class="form-grid"><label>Nombre o alias<input class="form-control" name="name" required></label><label>Edad<input class="form-control" name="age" type="number" min="5" max="120"></label><label class="full">Alergias conocidas<input class="form-control" name="allergies" placeholder="Ej.: penicilina"></label><label>Contacto de emergencia<input class="form-control" name="contact" placeholder="Nombre"></label><label>Teléfono<input class="form-control" name="phone" type="tel"></label><label class="full">Dato importante<textarea class="form-control" name="notes" rows="3" placeholder="Solo información necesaria"></textarea></label><button class="primary-btn full" type="submit">Guardar en este dispositivo</button></form>`,
 reminders:()=>`<span class="kicker">ORGANIZA TU CUIDADO</span><h2 id="modalTitle">Recordatorios</h2><p class="modal-lead">Medic no prescribe medicamentos. Registra solo indicaciones dadas por un profesional o actividades saludables.</p><form id="reminderForm" class="form-grid"><label class="full">Recordatorio<input class="form-control" name="title" required placeholder="Ej.: cita en el centro de salud"></label><label>Fecha<input class="form-control" type="date" name="date" required></label><label>Hora<input class="form-control" type="time" name="time" required></label><button class="primary-btn full" type="submit">Guardar recordatorio</button></form><div id="reminderList" class="saved-list"></div>`,
 data:()=>`<span class="kicker">CONTROL DE DATOS</span><h2 id="modalTitle">Mi base de datos local</h2><p class="modal-lead">Consulta cuántos registros existen. Puedes exportarlos o borrarlos en cualquier momento.</p><div id="dataStats" class="saved-list"><p>Cargando...</p></div><div class="hero-actions"><button class="primary-btn" id="exportData">Descargar copia JSON</button><button class="secondary-btn" id="deleteData">Borrar todos los datos</button></div>`
};
function openFeature(type){if(type==='chat')return startChat();showModal(templates[type]?.()||'<h2>Función en desarrollo</h2>');wireModal(type)}
function wireModal(type){if(type==='emergency')document.querySelector('#shareLocation')?.addEventListener('click',shareLocation);if(type==='firstAid')document.querySelectorAll('[data-aid]').forEach(b=>b.onclick=()=>showAid(b.dataset.aid));if(type==='calm')document.querySelector('#startCalm')?.addEventListener('click',startCalm);if(type==='profile')document.querySelector('#profileForm')?.addEventListener('submit',saveProfile);if(type==='reminders'){document.querySelector('#reminderForm')?.addEventListener('submit',saveReminder);renderReminders()}if(type==='data')renderDataPanel()}

const symptoms=['Dolor de cabeza','Fiebre o escalofríos','Dolor de estómago','Tos o malestar respiratorio','Mareo o debilidad','Otro malestar'];let chatState={symptom:'',redFlags:false};
function startChat(){chatState={symptom:'',redFlags:false};showModal(`<span class="kicker">ORIENTACIÓN PREVENTIVA</span><h2 id="modalTitle">Conversa con Medic</h2><div id="chatFlow"><div class="chat-bubble">¡Hola! Te haré preguntas breves para orientarte. No emitiré un diagnóstico. ¿Qué molestia principal tienes?</div><div class="choice-grid">${symptoms.map(s=>`<button class="choice-btn" data-symptom="${s}">${s}</button>`).join('')}</div></div>`);document.querySelectorAll('[data-symptom]').forEach(b=>b.onclick=()=>chooseSymptom(b.dataset.symptom))}
function chooseSymptom(symptom){chatState.symptom=symptom;document.querySelector('#chatFlow').innerHTML+=`<div class="chat-bubble user">${symptom}</div><div class="chat-bubble">Antes de continuar: ¿tienes dificultad intensa para respirar, dolor fuerte en el pecho, desmayo, confusión, sangrado abundante o empeoramiento rápido?</div><div class="choice-grid"><button class="choice-btn" data-red="yes">Sí, tengo una señal de alerta</button><button class="choice-btn" data-red="no">No</button></div>`;document.querySelectorAll('[data-red]').forEach(b=>b.onclick=()=>redFlag(b.dataset.red==='yes'))}
async function redFlag(isRed){chatState.redFlags=isRed;const flow=document.querySelector('#chatFlow');if(isRed){flow.innerHTML+=`<div class="alert-box"><strong>Busca ayuda inmediata.</strong><br>No continúes usando el orientador. Avisa a un adulto y llama al SAMU 106 o acude al servicio de emergencia más cercano.</div><button class="emergency-btn" data-open="emergency">Abrir centro de emergencia</button>`}else{flow.innerHTML+=`<div class="chat-bubble">Entiendo. ¿Desde cuándo tienes este malestar?</div><div class="choice-grid"><button class="choice-btn" data-time="hoy">Empezó hoy</button><button class="choice-btn" data-time="dias">Hace varios días</button><button class="choice-btn" data-time="repite">Se repite con frecuencia</button><button class="choice-btn" data-time="no-se">No estoy seguro</button></div>`;document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>finishChat(b.dataset.time))}await addRecord('interactions',{type:'symptom',symptom:chatState.symptom,redFlag:isRed})}
async function finishChat(time){document.querySelector('#chatFlow').innerHTML+=`<div class="chat-bubble user">${{hoy:'Empezó hoy',dias:'Hace varios días',repite:'Se repite con frecuencia','no-se':'No estoy seguro'}[time]}</div><div class="safe-box"><strong>Orientación general</strong><br>Descansa, mantente hidratado si puedes hacerlo con normalidad y cuéntaselo a un adulto de confianza. Si el malestar persiste, se repite o empeora, comunícate con la Línea 113 o acude a un centro de salud. No te automediques.</div><button class="secondary-btn" id="nearFromChat">📍 Buscar un centro cercano</button>`;document.querySelector('#nearFromChat').onclick=findNearby;await addRecord('interactions',{type:'orientation-complete',symptom:chatState.symptom,duration:time});showToast('Orientación guardada de forma local')}

const aid={bleeding:{title:'Sangrado',steps:['Pide ayuda a un adulto y usa protección si está disponible.','Aplica presión firme y continua con una tela o gasa limpia.','No retires objetos incrustados ni levantes la tela repetidamente.','Si el sangrado es abundante o no se controla, llama al 106.']},burn:{title:'Quemadura',steps:['Aleja a la persona de la fuente de calor sin ponerte en riesgo.','Enfría la zona con agua corriente fresca durante varios minutos.','Retira accesorios cercanos solo si no están adheridos.','No uses hielo, pasta dental, aceites ni revientes ampollas. Busca atención si es extensa o grave.']},faint:{title:'Desmayo',steps:['Comprueba si responde y si respira normalmente.','Si respira, acuéstala boca arriba y eleva ligeramente las piernas si no hay lesión.','Afloja ropa apretada y mantén ventilado el lugar.','Si no despierta pronto, se golpeó o respira de forma anormal, llama al 106.']},choke:{title:'Atragantamiento',steps:['Pregunta si puede toser o hablar. Si puede, anímala a toser.','Si no puede respirar, hablar o toser, pide ayuda inmediata y llama al 106.','Solicita a una persona capacitada que realice las maniobras de desobstrucción.','Si pierde el conocimiento, sigue las indicaciones del operador de emergencias.']},sprain:{title:'Golpe o torcedura',steps:['Detén la actividad y protege la zona.','Coloca frío envuelto en una tela por periodos cortos; nunca directo sobre la piel.','Eleva la extremidad si resulta cómodo.','Busca evaluación si hay deformidad, dolor intenso, adormecimiento o no puede apoyar.']},fever:{title:'Fiebre o malestar',steps:['Informa a un adulto y descansa.','Bebe líquidos si puedes hacerlo con normalidad.','No tomes medicamentos sin indicación de un adulto responsable o profesional.','Busca atención si aparece dificultad para respirar, confusión, convulsión, rigidez de cuello o empeoramiento.']}};
function showAid(key){const a=aid[key];showModal(`<button class="secondary-btn" id="backAid">← Volver</button><h2 id="modalTitle">${a.title}</h2><ol class="steps">${a.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="alert-box">Ante peligro inmediato o una situación grave, llama al SAMU 106.</div>`);document.querySelector('#backAid').onclick=()=>openFeature('firstAid');addRecord('interactions',{type:'first-aid',guide:key})}
function startCalm(){let remaining=60;const btn=document.querySelector('#startCalm');const timer=document.querySelector('#calmTimer');const circle=document.querySelector('#breathCircle');btn.disabled=true;const phases=['Inhala','Sostén','Exhala','Descansa'];let phase=0;circle.textContent=phases[0];const phaseTimer=setInterval(()=>{phase=(phase+1)%4;circle.textContent=phases[phase]},4000);const interval=setInterval(()=>{remaining--;timer.textContent=`00:${String(remaining).padStart(2,'0')}`;if(remaining<=0){clearInterval(interval);clearInterval(phaseTimer);circle.textContent='¡Muy bien!';btn.textContent='Repetir';btn.disabled=false;timer.textContent='Completado';addRecord('interactions',{type:'calm-exercise',seconds:60});showToast('Ejercicio completado')}} ,1000)}
async function saveProfile(e){e.preventDefault();await addRecord('profiles',Object.fromEntries(new FormData(e.target)));showToast('Ficha guardada en este dispositivo');closeModal()}
async function saveReminder(e){e.preventDefault();await addRecord('reminders',Object.fromEntries(new FormData(e.target)));e.target.reset();showToast('Recordatorio guardado');renderReminders()}
async function renderReminders(){const list=document.querySelector('#reminderList');if(!list)return;const items=await getAll('reminders');list.innerHTML=items.length?items.map(x=>`<div class="saved-item"><div><strong>${escapeHTML(x.title)}</strong><small>${x.date} · ${x.time}</small></div><span>🔔</span></div>`).join(''):'<p class="modal-lead">Aún no hay recordatorios guardados.</p>'}
async function renderDataPanel(){const stats=document.querySelector('#dataStats');const all={};for(const store of ['profiles','interactions','reminders','feedback'])all[store]=await getAll(store);stats.innerHTML=`<div class="saved-item"><strong>Fichas preventivas</strong><span>${all.profiles.length}</span></div><div class="saved-item"><strong>Interacciones</strong><span>${all.interactions.length}</span></div><div class="saved-item"><strong>Recordatorios</strong><span>${all.reminders.length}</span></div><div class="saved-item"><strong>Opiniones</strong><span>${all.feedback.length}</span></div>`;document.querySelector('#exportData').onclick=()=>exportData(all);document.querySelector('#deleteData').onclick=async()=>{if(confirm('¿Borrar todos los datos guardados por este prototipo en este navegador?')){await clearAll();showToast('Datos eliminados');renderDataPanel()}}}
function exportData(all){const blob=new Blob([JSON.stringify({app:'Bot Medic al Rescate',school:'Colegio Rosas Pata',exportedAt:new Date().toISOString(),data:all},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bot-medic-datos-locales.json';a.click();URL.revokeObjectURL(a.href)}
function escapeHTML(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function findNearby(){if(!navigator.geolocation){return window.open('https://www.google.com/maps/search/centro+de+salud+cerca','_blank')}showToast('Solicitando permiso de ubicación...');navigator.geolocation.getCurrentPosition(p=>{window.open(`https://www.google.com/maps/search/centro+de+salud/@${p.coords.latitude},${p.coords.longitude},14z`,'_blank');addRecord('interactions',{type:'nearby-search',locationGranted:true})},()=>{showToast('No se pudo usar la ubicación. Abriremos una búsqueda general.');window.open('https://www.google.com/maps/search/centro+de+salud+cerca','_blank')},{enableHighAccuracy:false,timeout:8000})}
function shareLocation(){if(!navigator.geolocation)return showToast('Este navegador no permite obtener la ubicación');navigator.geolocation.getCurrentPosition(async p=>{const url=`https://maps.google.com/?q=${p.coords.latitude},${p.coords.longitude}`;try{await navigator.share({title:'Mi ubicación de emergencia',text:'Esta es mi ubicación actual:',url})}catch{await navigator.clipboard?.writeText(url);showToast('Enlace de ubicación copiado')}} ,()=>showToast('No se concedió permiso de ubicación'))}
document.querySelector('#nearbyBtn').onclick=findNearby;document.querySelector('#mapCardBtn').onclick=findNearby;
document.querySelector('#fontBtn').onclick=()=>{document.documentElement.classList.toggle('font-large');showToast(document.documentElement.classList.contains('font-large')?'Letra grande activada':'Tamaño normal')};document.querySelector('#contrastBtn').onclick=()=>{document.body.classList.toggle('high-contrast');showToast('Contraste actualizado')};
document.querySelector('#feedbackForm').addEventListener('submit',async e=>{e.preventDefault();await addRecord('feedback',Object.fromEntries(new FormData(e.target)));e.target.reset();showToast('¡Gracias! Tu opinión fue guardada')});
openDB().catch(()=>showToast('La base de datos local no está disponible en este navegador'));
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
